---
consumer_key: PUT YOUR TWITTER CONSUMER KEY HERE
consumer_secret: PUT YOUR TWITTER CONSUMER SECRET KEY HERE
oauth_token: PUT YOUR TWITTER OATH TOKEN HERE
oauth_secret: PUT YOUR TWITTER OATH SECRET KEY HERE
twitter_users:
  - 
    screen_name: PUT SCREEN NAME HERE (no @)
    display_name: PUT NAME FOR DISPLAY HERE
  - 
    screen_name: PUT ANOTHER SCREEN NAME HERE (no @)
    display_name: PUT ANOTHER NAME FOR DISPLAY HERE